# Generated by Django 4.1.5 on 2023-01-19 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_post', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Author',
            new_name='author',
        ),
    ]
