# Generated by Django 4.1.5 on 2023-01-20 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_post', '0006_rename_likes_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like_count',
        ),
    ]
