# Generated by Django 4.1.5 on 2023-01-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_post', '0008_alter_like_author_alter_like_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
