# Generated by Django 4.1.5 on 2023-01-23 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_post', '0010_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='author',
            new_name='liked_by',
        ),
    ]
