# Generated by Django 4.1.5 on 2023-01-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_post', '0012_rename_author_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
