# Generated by Django 4.1.5 on 2023-01-24 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_post', '0014_rename_user_comment_comment_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_by',
            new_name='commented_by',
        ),
    ]
